=== concepting-com-br/framework/bin/main/etc/resources/networkResources.xsd
<xs:schema attributeFormDefault="unqualified" 
           elementFormDefault="qualified" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="network">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="mail" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="resources" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="storage" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="serverName" minOccurs="1" maxOccurs="1"/>
													<xs:element type="xs:byte" name="serverPort" minOccurs="1" maxOccurs="1"/>
													<xs:element type="xs:string" name="userName" minOccurs="0" maxOccurs="1"/>
													<xs:element type="xs:string" name="password" minOccurs="0" maxOccurs="1"/>
												</xs:sequence>
												<xs:attribute name="type" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:enumeration value="POP3"/>
															<xs:enumeration value="IMAP"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute type="xs:boolean" name="useSsl"/>
												<xs:attribute type="xs:boolean" name="useTls"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="transport" minOccurs="0"
											maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="serverName" minOccurs="1" maxOccurs="1"/>
													<xs:element type="xs:byte" name="serverPort" minOccurs="1" maxOccurs="1"/>
													<xs:element type="xs:string" name="userName" minOccurs="0" maxOccurs="1"/>
													<xs:element type="xs:string" name="password" minOccurs="0" maxOccurs="1"/>
												</xs:sequence>
												<xs:attribute name="type" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:enumeration value="ESMTP"/>
															<xs:enumeration value="SMTP"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute type="xs:boolean" name="useSsl"/>
												<xs:attribute type="xs:boolean" name="useTls"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="id"/>
									<xs:attribute type="xs:boolean" name="default"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="ldap" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="resources" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="serverName" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:short" name="serverPort" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:string" name="authenticationType" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:string" name="userName" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:string" name="password" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:string" name="baseDn" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:string" name="userDn" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:short" name="timeout" minOccurs="0" maxOccurs="1"/>
									</xs:sequence>
									<xs:attribute type="xs:string" name="id" use="required"/>
									<xs:attribute type="xs:string" name="factoryResourcesId" use="optional"/>
									<xs:attribute type="xs:boolean" name="default" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="webService" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="resources" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="method" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:short" name="timeout" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:string" name="url" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:string" name="data" minOccurs="0" maxOccurs="1"/>
										<xs:element name="headers" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="header" minOccurs="1" maxOccurs="unbounded">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:string" name="id" use="required"/>
																	<xs:attribute type="xs:string" name="value" use="optional"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="id" use="required"/>
									<xs:attribute type="xs:boolean" name="default" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="mq" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="resources" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="serverName" minOccurs="0" maxOccurs="1"/>
										<xs:element type="xs:short" name="serverPort" minOccurs="0" maxOccurs="1"/>
										<xs:element name="queues" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="queue" minOccurs="1" maxOccurs="unbounded">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:string" name="id" use="required"/>
																	<xs:attribute type="xs:string" name="listenerClass" use="optional"/>
																	<xs:attribute type="xs:integer" name="size" use="optional"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="id" use="required"/>
									<xs:attribute type="xs:boolean" name="default" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== concepting-com-br/framework/bin/main/etc/resources/networkResources.xml
<?xml version="1.0" encoding="utf-8"?>
 
<network xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="networkResources.xsd">
	<mail>
		<resources id="localhost" default="true"/>
	</mail>
	<ldap>
		<resources id="localhost" factoryResourcesId="ldap" default="true"/>
	</ldap>
	<webService>
		<resources id="localhost" default="true"/>
	</webService>
	<mq>
		<resources id="localhost" default="true"/>
	</mq>
</network>
