=== concepting-com-br/framework/src/main/resources/etc/resources/systemResources.xsd
<xs:schema attributeFormDefault="unqualified" 
           elementFormDefault="qualified" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
 	<xs:element name="resources">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="packagesPrefix" minOccurs="1" maxOccurs="1"/>
				<xs:element name="mainConsole" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="class" minOccurs="0" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="languages" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="language" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="id" use="required"/>
											<xs:attribute type="xs:boolean" name="default" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="skins" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="skin" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="id" use="required"/>
											<xs:attribute type="xs:boolean" name="default" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="actionForms" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="actionForm" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="forwards" minOccurs="1" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="forward" minOccurs="1" maxOccurs="unbounded">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:string" name="name" use="required"/>
																	<xs:attribute type="xs:string" name="url" use="required"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="required"/>
									<xs:attribute type="xs:string" name="action" use="required"/>
									<xs:attribute type="xs:string" name="class" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== concepting-com-br/framework/src/main/resources/etc/resources/systemResources.xml
<?xml version="1.0" encoding="UTF-8"?>

<resources xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="systemResources.xsd">
    <packagesPrefix></packagesPrefix>
    <mainConsole></mainConsole>  
    <languages> 
        <language id="pt_BR" default="true"></language>  
        <language id="en_US"></language>  
        <language id="es"></language> 
    </languages>  
    <skins> 
        <skin id="default" default="true"></skin> 
    </skins>  
    <actionForms/> 
</resources>
